FROM eclipse-temurin:17-jdk

RUN useradd --create-home --shell /bin/bash appuser
USER appuser
WORKDIR /home/appuser

COPY app/target/devops2-mukhanovt-1.0.0.jar app.jar

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD curl -f http://localhost:8090/actuator/health || exit 1

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "app.jar"]